version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: my-secret-pw

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
