version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: my-secret-pw

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - my-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
