[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
rocket_cors = "0.5.2"
rocket_contrib = { version = "0.4.11", default-features = false, features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
